model_list:
  # --- Smart Group ---
  - model_name: smart
    litellm_params:
      model: azure/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/OPENAI_AZURE_ENDPOINT
      api_version: os.environ/OPENAI_API_VERSION
#  - model_name: smart
#    litellm_params:
#      model: anthropic/claude-3-5-sonnet-20241022
#      api_key: os.environ/ANTHROPIC_API_KEY

  # --- Fast Group ---
  - model_name: fast
    litellm_params:
      model: azure/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/OPENAI_AZURE_ENDPOINT
      api_version: os.environ/OPENAI_API_VERSION

  # --- Default Group ---
  - model_name: default
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: os.environ/GEMINI_API_KEY
  - model_name: default
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: os.environ/GEMINI_API_KEY

router_settings:
  routing_strategy: simple-shuffle
  fallbacks:
    - "smart": ["fast"]
    - "fast": ["default"]
